import { LanguageDefinition, VoiceDefinition } from './types';

export const DEFAULT_API_URL = "https://testbed3.zinterview.ai/api/external-services/textToSpeechGC";

export const SUPPORTED_VOICES: VoiceDefinition[] = [
  { name: "Zephyr", description: "Bright" },
  { name: "Puck", description: "Upbeat" },
  { name: "Charon", description: "Informative" },
  { name: "Kore", description: "Firm" },
  { name: "Fenrir", description: "Excitable" },
  { name: "Leda", description: "Youthful" },
  { name: "Orus", description: "Firm" },
  { name: "Aoede", description: "Breezy" },
  { name: "Callirrhoe", description: "Easy-going" },
  { name: "Autonoe", description: "Bright" },
  { name: "Enceladus", description: "Breathy" },
  { name: "Iapetus", description: "Clear" },
  { name: "Umbriel", description: "Easy-going" },
  { name: "Algieba", description: "Smooth" },
  { name: "Despina", description: "Smooth" },
  { name: "Erinome", description: "Clear" },
  { name: "Algenib", description: "Gravelly" },
  { name: "Rasalgethi", description: "Informative" },
  { name: "Laomedeia", description: "Upbeat" },
  { name: "Achernar", description: "Soft" },
  { name: "Alnilam", description: "Firm" },
  { name: "Schedar", description: "Even" },
  { name: "Gacrux", description: "Mature" },
  { name: "Pulcherrima", description: "Forward" },
  { name: "Achird", description: "Friendly" },
  { name: "Zubenelgenubi", description: "Casual" },
  { name: "Vindemiatrix", description: "Gentle" },
  { name: "Sadachbia", description: "Lively" },
  { name: "Sadaltager", description: "Knowledgeable" },
  { name: "Sulafat", description: "Warm" },
];

export const DEFAULT_TEXTS: Record<string, string> = {
  "af": "Hierdie is 'n toets vir die teks-na-spraak stelsel. Dit demonstreer hoe natuurlik die stemme kan klink wanneer langer paragrawe gelees word.",
  "ar": "هذا اختبار لنظام تحويل النص إلى كلام. تتيح لنا هذه التقنية سماع النصوص المكتوبة بأصوات طبيعية ومتنوعة، مما يسهل التواصل عبر اللغات المختلفة.",
  "bg": "Това е тест на системата за преобразуване на текст в реч. Технологията позволява по-добро взаимодействие с компютърните системи чрез гласови команди и синтезиран говор.",
  "ca": "Això és una prova del sistema de text a veu. Aquesta tecnologia permet convertir text escrit en paraules parlades amb una intonació i ritme naturals.",
  "cs": "Toto je test systému převodu textu na řeč. Syntéza řeči se stává stále důležitější součástí moderních aplikací a usnadňuje přístup k informacím.",
  "da": "Dette er en test af tekst-til-tale-systemet. Det viser, hvordan kunstig intelligens kan bruges til at generere naturtro tale på forskellige sprog.",
  "de": "Dies ist ein Test des Text-zu-Sprache-Systems. Die Qualität der synthetischen Stimmen hat sich in den letzten Jahren erheblich verbessert, was natürlichere Gespräche ermöglicht.",
  "el": "Αυτή είναι μια δοκιμή του συστήματος κειμένου σε ομιλία. Η τεχνολογία αυτή επιτρέπει την ακουστική αναπαραγωγή γραπτού κειμένου με φυσικότητα και ακρίβεια.",
  "en": "This is a comprehensive test of the text-to-speech generation system. By providing a longer paragraph, we can better evaluate the flow, intonation, and naturalness of the selected voice across multiple sentences.",
  "es": "Esta es una prueba del sistema de texto a voz. La tecnología ha avanzado mucho, permitiendo una entonación más natural y fluida que se asemeja mucho al habla humana real en diversos contextos.",
  "fi": "Tämä on tekstistä puheeksi -järjestelmän testi. Puhesynteesi on kehittynyt huimasti, ja nykyään koneet voivat puhua lähes yhtä luontevasti kuin ihmiset.",
  "fr": "Ceci est un test du système de synthèse vocale. Il permet d'évaluer la fluidité de la voix et la précision de la prononciation sur des phrases plus longues et plus complexes.",
  "gl": "Esta é unha proba do sistema de texto a voz. A xeración de voz artificial mellorou notablemente, permitindo unha comunicación máis accesible para todos.",
  "he": "זוהי בדיקה של מערכת טקסט לדיבור. הטכנולוגיה מאפשרת להמיר טקסט כתוב לדיבור שוטף וטבעי, מה שמשפר את הנגישות ומאפשר יישומים חדשים.",
  "hi": "यह टेक्स्ट-टू-स्पीच सिस्टम का परीक्षण है। आधुनिक तकनीक ने कंप्यूटर को इंसान की तरह बोलने की क्षमता दी है, जिससे जानकारी तक पहुंचना आसान हो गया है।",
  "hu": "Ez a szöveg-beszéd rendszer tesztje. A mesterséges intelligencia segítségével a gépi hangok egyre természetesebben hangzanak, megkönnyítve az ember-gép kommunikációt.",
  "id": "Ini adalah tes sistem text-to-speech. Dengan teknologi ini, komputer dapat membacakan teks dengan intonasi yang wajar, membantu dalam berbagai aplikasi sehari-hari.",
  "is": "Þetta er prófun á texta-í-tal kerfinu. Tæknin hefur fleygt fram og gerir tölvum kleift að tala íslensku með eðlilegum hætti og réttum framburði.",
  "it": "Questa è una prova del sistema di sintesi vocale. L'obiettivo è verificare come la voce gestisce la punteggiatura e l'intonazione in un discorso più articolato e lungo.",
  "ja": "これはテキスト読み上げシステムのテストです。長い文章を入力することで、音声の自然さや抑揚、リズムを確認することができます。技術の進歩により、より人間らしい発話が可能になりました。",
  "kn": "ಇದು ಪಠ್ಯದಿಂದ ಧ್ವನಿ ವ್ಯವಸ್ಥೆಯ ಪರೀಕ್ಷೆಯಾಗಿದೆ. ತಂತ್ರಜ್ಞಾನವು ಬಹಳಷ್ಟು ಮುಂದುವರಿದಿದೆ, ಮತ್ತು ಈಗ ಕಂಪ್ಯೂಟರ್‌ಗಳು ಮನುಷ್ಯರಂತೆ ಮಾತನಾಡಬಲ್ಲವು.",
  "ko": "이것은 텍스트 음성 변환 시스템의 테스트입니다. 긴 문장을 통해 음성 합성 기술의 자연스러움과 정확성을 평가할 수 있으며, 다양한 억양을 확인하는 데 도움이 됩니다.",
  "lt": "Tai teksto vertimo į kalbą sistemos bandymas. Ši technologija leidžia kompiuteriams skaityti tekstą balsu, o tai labai naudinga įvairiose srityse.",
  "lv": "Šis ir teksta-runas sistēmas tests. Mūsdienu risinājumi ļauj ģenerēt balsi, kas skan ļoti dabiski un saprotami, uzlabojot lietotāja pieredzi.",
  "mr": "ही टेक्स्ट-टू-स्पीच सिस्टमची चाचणी आहे. तंत्रज्ञानाच्या प्रगतीमुळे आता संगणक मानवी आवाजाप्रमाणेच बोलू शकतात, ज्यामुळे संवाद अधिक सोपा झाला आहे.",
  "ms": "Ini adalah ujian sistem teks-ke-ucapan. Teknologi ini membolehkan teks dibaca dengan lancar dan jelas, memberikan pengalaman yang lebih baik kepada pengguna.",
  "nl": "Dit is een test van het tekst-naar-spraak systeem. We testen hierbij de uitspraak van langere zinnen en de natuurlijke pauzes die de stem maakt tijdens het spreken.",
  "no": "Dette er en test av tekst-til-tale-systemet. Ved å bruke lengre setninger kan vi bedre vurdere hvor naturlig stemmen høres ut i en sammenhengende kontekst.",
  "pl": "To jest test systemu zamiany tekstu na mowę. Dzięki zaawansowanym algorytmom, syntezatory mowy potrafią teraz naśladować ludzką intonację z dużą precyzją.",
  "pt": "Este é um teste do sistema de texto para fala. A capacidade de converter texto em áudio de alta qualidade abre muitas portas para acessibilidade e novas interfaces de usuário.",
  "ro": "Acest lucru este un test al sistemului text-to-speech. Tehnologia modernă permite generarea unei voci clare și naturale, esențială pentru aplicațiile interactive.",
  "ru": "Это тест системы преобразования текста в речь. Длинные тексты позволяют оценить качество интонации и правильность ударений в сложных предложениях.",
  "sk": "Toto je test systému prevodu textu na reč. Syntetické hlasy sú dnes už takmer na nerozoznanie od ľudských, čo zlepšuje interakciu s technológiami.",
  "sr": "Ово је тест система за претварање текста у говор. Ова технологија омогућава рачунарима да читају текст природним гласом, што је корисно за многе примене.",
  "sv": "Detta är ett test av text-till-tal-systemet. Genom att använda längre texter kan vi se hur väl systemet hanterar prosodi och satsmelodi i det svenska språket.",
  "ta": "இது உரையிலிருந்து பேச்சு மாற்றும் அமைப்பின் சோதனையாகும். தொழில்நுட்பம் வளர்ந்துள்ளதால், கணினிகள் இப்போது மனிதர்களைப் போலவே தெளிவாகப் பேசுகின்றன.",
  "te": "ಇದು ಪಠ್ಯದಿಂದ ಧ್ವನಿ ವ್ಯವಸ್ಥೆಯ ಪರೀಕ್ಷೆಯಾಗಿದೆ.", 
  "th": "นี่คือการทดสอบระบบแปลงข้อความเป็นเสียง การทดสอบด้วยประโยคยาวๆ ช่วยให้เราเห็นถึงความลื่นไหลและความเป็นธรรมชาติของเสียงสังเคราะห์ได้ดียิ่งขึ้น",
  "tr": "Bu, metin okuma sisteminin bir testidir. Gelişmiş yapay zeka modelleri sayesinde, bilgisayarlar artık metinleri insan benzeri bir doğallıkla seslendirebiliyor.",
  "uk": "Це тест системи перетворення тексту в мовлення. Сучасні технології дозволяють створювати голоси, які звучать природно і емоційно, покращуючи комунікацію.",
  "vi": "Đây là thử nghiệm của hệ thống chuyển văn bản thành giọng nói. Công nghệ này giúp máy tính đọc văn bản một cách trôi chảy, hỗ trợ người dùng tiếp cận thông tin dễ dàng hơn.",
};

// Mapped from the user's switch statement provided in the prompt
export const SUPPORTED_LANGUAGES: LanguageDefinition[] = [
  { code: "af", name: "Afrikaans", backendMapping: ["af-ZA"] },
  { code: "ar", name: "Arabic", backendMapping: ["ar-XA", "ar-XA-Standard-B"] },
  { code: "bg", name: "Bulgarian", backendMapping: ["bg-BG"] },
  { code: "ca", name: "Catalan", backendMapping: ["ca-ES"] },
  { code: "cs", name: "Czech", backendMapping: ["cs-CZ"] },
  { code: "da", name: "Danish", backendMapping: ["da-DK"] },
  { code: "de", name: "German", backendMapping: ["de-DE", "de-DE-Standard-B"] },
  { code: "el", name: "Greek", backendMapping: ["el-GR"] },
  { code: "en", name: "English", backendMapping: ["en-US"] },
  { code: "es", name: "Spanish", backendMapping: ["es-ES", "es-ES-Neural2-B"] },
  { code: "fi", name: "Finnish", backendMapping: ["fi-FI"] },
  { code: "fr", name: "French", backendMapping: ["fr-CA", "fr-CA-Standard-B"] },
  { code: "gl", name: "Galician", backendMapping: ["gl-ES"] },
  { code: "he", name: "Hebrew", backendMapping: ["he-IL"] },
  { code: "hi", name: "Hindi", backendMapping: ["hi-IN", "hi-IN-Neural2-B"] },
  { code: "hu", name: "Hungarian", backendMapping: ["hu-HU"] },
  { code: "id", name: "Indonesian", backendMapping: ["id-ID"] },
  { code: "is", name: "Icelandic", backendMapping: ["is-IS"] },
  { code: "it", name: "Italian", backendMapping: ["it-IT", "it-IT-Standard-C"] },
  { code: "ja", name: "Japanese", backendMapping: ["ja-JP", "ja-JP-Standard-C"] },
  { code: "kn", name: "Kannada", backendMapping: ["kn-IN", "kn-IN-Standard-B"] },
  { code: "ko", name: "Korean", backendMapping: ["ko-KR", "ko-KR-Standard-C"] },
  { code: "lt", name: "Lithuanian", backendMapping: ["lt-LT"] },
  { code: "lv", name: "Latvian", backendMapping: ["lv-LV"] },
  { code: "mr", name: "Marathi", backendMapping: ["mr-IN", "mr-IN-Standard-B"] },
  { code: "ms", name: "Malay", backendMapping: ["ms-MY", "ms-MY-Standard-B"] },
  { code: "nl", name: "Dutch", backendMapping: ["nl-BE"] },
  { code: "no", name: "Norwegian", backendMapping: ["nb-NO", "nb-NO-Standard-B"] },
  { code: "pl", name: "Polish", backendMapping: ["pl-PL", "pl-PL-Standard-C"] },
  { code: "pt", name: "Portuguese", backendMapping: ["pt-BR", "pt-BR-Standard-B"] },
  { code: "ro", name: "Romanian", backendMapping: ["ro-RO", "ro-RO-Standard-A"] },
  { code: "ru", name: "Russian", backendMapping: ["ru-RU", "ru-RU-Standard-B"] },
  { code: "sk", name: "Slovak", backendMapping: ["sk-SK", "sk-SK-Standard-A"] },
  { code: "sr", name: "Serbian", backendMapping: ["sr-RS"] },
  { code: "sv", name: "Swedish", backendMapping: ["sv-SE", "sv-SE-Standard-D"] },
  { code: "ta", name: "Tamil", backendMapping: ["ta-IN", "ta-IN-Standard-B"] },
  { code: "te", name: "Telugu", backendMapping: ["te-IN", "te-IN-Chirp3-HD-Achird"] },
  { code: "th", name: "Thai", backendMapping: ["th-TH", "th-TH-Standard-A"] },
  { code: "tr", name: "Turkish", backendMapping: ["tr-TR", "tr-TR-Standard-B"] },
  { code: "uk", name: "Ukrainian", backendMapping: ["uk-UA", "uk-UA-Standard-A"] },
  { code: "vi", name: "Vietnamese", backendMapping: ["vi-VN", "vi-VN-Standard-B"] },
].sort((a, b) => a.name.localeCompare(b.name));
